---
- name: Disable swap
  command: swapoff -a
  changed_when: false
  tags: ["notest"]

- name: Add swapfile to /etc/fstab
  mount:
    dump: "0"
    fstype: swap
    name: none
    opts: sw
    passno: "0"
    src: "{{ swap_file }}"
    state: absent

- name: Ensure swap file is deleted
  file:
    path: "{{ swap_file }}"
    state: absent
