---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false
  tags: ["notest"]

- name: Add swapfile to /etc/fstab
  ansible.posix.mount:
    dump: "0"
    fstype: swap
    name: none
    opts: sw
    passno: "0"
    src: "{{ swap_file }}"
    state: absent

- name: Ensure swap file is deleted
  ansible.builtin.file:
    path: "{{ swap_file }}"
    state: absent
