---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ swap_dependencies }}"
    state: present
    update_cache: true

- name: Include tasks to enable swap
  ansible.builtin.include_tasks: enable.yml
  when: swap_enabled | bool

- name: Include tasks to disable swap
  ansible.builtin.include_tasks: disable.yml
  when: not swap_enabled
