---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ swap_dependencies }}"
    state: present
    update_cache: true

- include_tasks: enable.yml
  when: swap_enabled | bool

- include_tasks: disable.yml
  when: not swap_enabled
