---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: ansible-role-swap-debian-11
    image: debian:11
    privileged: true
  - name: ansible-role-swap-debian-12
    image: debian:12
    privileged: true
  - name: ansible-role-swap-ubuntu-2204
    image: ubuntu:22.04
    privileged: true
  - name: ansible-role-swap-ubuntu-2404
    image: ubuntu:24.04
    privileged: true

provisioner:
  name: ansible

verifier:
  name: testinfra
